### ISSUE TITLE
Gregtech 6

### ISSUE THREAD

**Issue by leagris** [Soartex-Modded/Modded-1.7.x#72]
Gregtech 6 is the next in-dev version still for MC 1.7.x and is in Alpha stage.

We may start preparing assets for version 6.

I think it is appropriate to start pushing assets for Gregtech 6 now without breaking changes.
Currently textured version 5 never reached release, version 6 has been announced with more seamless upgrades and changes.

We can keep current branch and update json version as it will likely be possible to keep backward compatibility with Gregtech 5 without overloading the pack too much.
Directory structure has been stabilized in late version 5.

Good news:
http://files.minecraftforge.net/maven/com/gregoriust/gregtech/changelog.txt
[YES-IT-IS-FINALLY-FIXED] GT Blocks not being able to use Alpha in Textures.

It means we are now able to restore Soartex style Ores shine and cracks as OVERLAYS with an alpha channel and colorful PNGs. (Thank you @gregoriust for your work on this).
It has been a frustrating flat experience before, with version 5 meta generated textures limited to a hued icon overlay.

**Comment by artdude543** [comment]
Ahh awesome glad to hear that alpha textures are fixed. I'm happy if you want to use a Gregtech_6 folder for that version, if back support does not work. But knowing Greg he will add the support, but its an option.

If you're talking about making a whole new branch on the repo then this is something I would like to avoid, but creating a separate folder for the v6 is something I think would work better.

**Comment by leagris** [comment]
For now, tools and ores did not change.

Machine blocks and interfaces are not yet available.

Main incompatible changes will come from GUI layouts if using same asset names.

Version 5 is likely to die as an aborted newborn as soon as version 6 is feature paired, as both these are targeting the same MC version 1.7.x.

I currently have no Gregtech6 setup and only did some basic ore layer tests:

Base Ore Icon: (sample gem style)
Gregtech applies material hue tint and overlay base texture (stone, sandstone, granite...).
So it serve as a gray-scale luminance layer.
![Base Ore Icon](https://dl.dropboxusercontent.com/s/1sjcxabr4m4ev8g/ore.png)

Shine and cracks OVERLAY:
Gregtech will overlay this in full RGBA
![Shine and cracks OVERLAY](https://dl.dropbox.com/s/t7c7j5jfc8butab/ore_OVERLAY.png)

Rendering samples of Base material + Ore Icon + Overlay with a Diamond ore:

![Diamond Ore over vanilla stone](https://dl.dropbox.com/s/oyk12832f8by7a6/render_STONE.png) over vanilla stone
![Diamond Ore over vanilla sandstone](https://dl.dropbox.com/s/h7763j69h27rd4z/render_SANDSTONE.png) over vanilla sandstone
![Diamond Ore over red granite](https://dl.dropbox.com/s/65rerk05xnhrk4v/render_GRANITE_RED_STONE.png) over Gregtech red granite
![Diamond Ore over black granite](https://dl.dropbox.com/s/4c58la8f8qsko77/render_GRANITE_BLACK_STONE.png) over Gregtech black granite

**Comment by GregoriusT** [comment]
The old Packs will still work with GT 6 (since it will then take the
default Overlay Icons, which are all just an empty Texture and
therefore invisible), but new Packs probably won't work with GT 5, in
regards of the new Overlays of the upcoming Version (if you make use
of the Alpha Channel, if not, then it will just ignore the Overlays in
GT 5).

I'm not renaming already existing Textures, that would be a horrible
amount of work for me too.

The additional uncolored Overlay Textures for Blocks will have the
same "_OVERLAY"-ending the Item Textures have and are rendered right
after the regular colored Texture.

Aside from this additional Feature of allowing halftransparent
Textures for >>ALL<< Blocks in GT (without exception) there won't be
any changes to the already re-used Textures (Ores, Storage Blocks
etc.)

Machines however will change (including Texture Names, so those should
stay compatible between both Pack Versions), because their underlying
Functionality will be different, especially dedicated Energy and Item
Input Facings and similar.

2015-03-06 16:24 GMT, Léa Gris <notifications@github.com>:
