### ISSUE TITLE
Bulidcraft 7 has new assets path

### ISSUE THREAD

**Issue by jkroepke** [Soartex-Modded/Modded-1.7.x#98]
Hello,

Buildcraft 7 (Beta) is out.

The mod use now different assets, since this mod this modular.

See https://github.com/BuildCraft/BuildCraft/tree/7.0.4/buildcraft_resources/assets for the new folder structure.

I'm will be happy, if you support this new version.

**Comment by artdude543** [comment]
I'm going to send some time over the next day or two porting the textures to the new file path.

**Comment by Mystara0001** [comment]
I've already done this for the latest version of BuildCraft 7, I have not created any Untextured.txt files, and some of the textures could not be reused due to file changes. I'd be more than happy to upload this if you'd like.

My thought was to put it in a new floder named BuildCraft_7 since it is so dramatically different. Please let me know.

**Comment by leagris** [comment]
Sound good!

Don't forget to attribute a distinct mod_id like BuildCraft_7 into
`mod.json` like:

```JSON
{
  "mod_id": "BuildCraft",
  "mod_name": "Buildcraft",
  "mod_dir": "/Buildcraft/",
  "mod_version": "v7.0.6",
  "mc_version": "1.7.10",
  "mod_authors": ["SpaceToad", "BuildCraft Team"],
  "url_website": "http://www.mod-buildcraft.com/",
  "description": "Extending Minecraft with pipes, auto-crafting,
quarries, engines and much more!"
}
```

**Comment by artdude543** [comment]
This has been ported and updated downloads are being updated now, should be available on the CDN once it syncs to all the servers.
